#!/bin/sh

echo "Starting rcS..."

mkdir -p  /lib/modules/$(uname -r);
touch /lib/modules/$(uname -r)/modules.dep

syslogd -C400

echo "++ Mounting filesystem"
mkdir -p /dev/pts /dev/shm
mount -a

# PS1=DBG1: /bin/sh

echo "++ Mounting main fs"
if [ -e /mnt/rootfs.ext2.gz ]; then
	ln -s /bin/busybox /bin/awk
	[ -e /mnt/rootfs.ext2 ] && rm /mnt/rootfs.ext2
	echo "+++ first time extract /mnt/rootfs.ext2.gz boot .."
	(while [ 1 ]; do sleep 1; ls -l /mnt/rootfs.ext2 | awk '{ print $9" "$5 }'; done) & MON=$!
	(gunzip /mnt/rootfs.ext2.gz & wait)
	kill -9 $MON; wait
	rm /bin/awk
fi

mkdir /mnt2
mount -o loop,ro -t ext2 /mnt/rootfs.ext2 /mnt2
(cd /mnt2/usr
	for file in *; do
		case $file in
		local)
			echo skip $file;;
		share)
			mkdir -p /usr/share/;
			cp -a /mnt2/usr/share/udhcpc /usr/share;;
		*)
			if [ -d $file ]; then
				mkdir -p /usr/$file; mount --bin $file /usr/$file
			fi;;
		esac
	done
)

# fixup to protect existing packages
mkdir -p /usr/local/bin
ln -s /usr/bin/procServ /usr/local/bin
ln -s /usr/bin/expect /usr/local/bin

export PATH=$PATH:/usr/local/bin
export LD_LIBRARY_PATH=/usr/local/lib/

cat - >>/etc/profile <<EOF
export PATH=$PATH
export LD_LIBRARY_PATH=/usr/local/lib/
EOF

echo "++ Setting up mdev"

echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

# PS1=DBG2: /bin/sh

# the device driver is not creating this node, so for now
# create the devcfg device node manually

if [ ! -e /dev/xdevcfg ]
then
	mknod /dev/xdevcfg c 259 0
fi

echo "++ Setting hostname"
for x in $(cat /proc/cmdline)
do
	case $x in
	hostname=*) echo ${x##*=} >/etc/hostname;;
	esac
done

	
# PS1=DBG3: /bin/sh

hostname -F /etc/hostname
echo "++ Start Lo"
ifconfig lo up

echo "++ Networking .. assigning serial console, use CTRL-C to break"
if [ -e /mnt/local/network ]; then
	echo "++ Sourcing /mnt/network.."
	source /mnt/local/network
else
	/etc/network/default-networkrc
fi

[ -e /mnt/local/ntpd.conf ] && /mnt/local/ntpd.conf


# PS1=DBG4: /bin/sh

	
echo "++ Starting http daemon"
httpd -h /var/www

echo "++ Starting ssh daemon"
chmod 600 /etc/ssh/*
/usr/sbin/sshd


# PS1=DBG5: /bin/sh

if [ -f /mnt/init.sh ]
then
	echo "++ Running user script OVERRIDE init.sh from SD Card"
     	source /mnt/init.sh
else
	/sbin/load.packages /mnt/packages
fi

# PS1=DBG6: /bin/sh

if [ -x /mnt/local/rc.user ]; then
	echo ++ calling /mnt/local/rc.user
	/mnt/local/rc.user	
fi

# PS1=DBG7: /bin/sh

echo $(hostname) $(uptime) > /var/www/d-tacq/rc-local-complete
echo "++ rcS complete $(cat /var/www/d-tacq/rc-local-complete)"



